services:
  postgres:
    image: postgres:17-alpine3.21
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  backend:
    driver: bridge

volumes:
  data:
