services:
  api:
    build:
      context: .
      target: api
    ports:
      - "3001:3000"
    container_name: api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      CORS_ORIGIN: http://localhost:3000
      ADDRESS: 0.0.0.0:3000
      SESSION_SECRET: some_very_very_long_and_hard_to_guess_secret
    depends_on:
      - postgres

  web:
    build:
      context: .
      target: web
    ports:
      - "3000:3000"
    container_name: web
    environment:
      NODE_ENV: production
      SERVER_INTERNAL: http://api:3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    depends_on:
      - api

  postgres:
    image: postgres:17-alpine3.21
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  backend:
    driver: bridge

volumes:
  data:
